name: "Test edge function compatibility for NextJS"
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.netlify_auth_token }}
            NETLIFY_SITE_ID: ${{ secrets.netlify_site_id }}
            TEST_DEPLOYED_VERSION: true
        defaults:
            run:
                working-directory: examples/next/with-emailpassword
        steps:
            - uses: actions/checkout@v2
            - run: echo $GITHUB_SHA
            - run: npm install git+https://github.com:supertokens/supertokens-node.git#$GITHUB_SHA
            - run: npm install
            - run: npm install mocha@6.1.4 jsdom-global@3.0.2 puppeteer@^11.0.0 isomorphic-fetch@^3.0.0

            # Step to update the runtime to edge to all files in app/api/ and pages/api/
            - name: Add runtime export to API files
              run: |
                  find app/api -type f -name "*.js" -exec sed -i '1s/^/export const runtime = "edge";\n/' {} +
                  find pages/api -type f -name "*.js" -exec sed -i '1s/^/export const runtime = "edge";\n/' {} +

            - run: netlify deploy --alias 0 --build --json --auth=$NETLIFY_AUTH_TOKEN > deployInfo.json
            - run: cat deployInfo.json
            - run: |
                  ( \
                    (echo "=========== Test attempt 1 ===========" && npx mocha --no-config --timeout 80000 test/**/*.test.js) || \
                    (echo "=========== Test attempt 2 ===========" && npx mocha --no-config --timeout 80000 test/**/*.test.js) || \
                    (echo "=========== Test attempt 3 ===========" && npx mocha --no-config --timeout 80000 test/**/*.test.js) \
                  )
            - name: The job has failed
              if: ${{ failure() }}
              uses: actions/upload-artifact@v3
              with:
                  name: screenshots
                  path: |
                      ./**/*screenshot.jpeg
