name: "Test edge function compatibility for Next.js on Cloudflare Workers"
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            TEST_DEPLOYED_VERSION: true
        defaults:
            run:
                working-directory: examples/next/with-emailpassword
        steps:
            - uses: actions/checkout@v2
            - run: echo $GITHUB_SHA
            - run: npm install git+https://github.com:supertokens/supertokens-node.git#$GITHUB_SHA
            - run: npm install
            - run: npm install mocha@6.1.4 jsdom-global@3.0.2 puppeteer@^11.0.0 isomorphic-fetch@^3.0.0

            # Step to update the runtime to edge to all files in app/api/ and pages/api/
            - name: Add runtime export to API files
              run: |
                  find app/api -type f \( -name "*.js" -o -name "*.ts" \) -exec sed -i '1s/^/export const runtime = "edge";\n/' {} +
                  find pages/api -type f \( -name "*.js" -o -name "*.ts" \) -exec sed -i '1s/^/export const runtime = "edge";\n/' {} +
                  echo 'export const runtime = "edge";' >> app/auth/[[...path]]/page.tsx
                  echo 'export const runtime = "edge";' >> pages/api/auth/[[...path]].tsx

            - name: Install next-on-pages
              run: npm install --save-dev @cloudflare/next-on-pages

            - name: Create a wrangler.toml
              run: echo "compatibility_flags = [ "nodejs_compat" ]" >> wrangler.toml

            - name: Build using next-on-pages
              run: npx next-on-pages

            - name: Publish to Cloudflare Pages
              id: deploy
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: "supertokens-node-pr-check-for-edge-function-compat"
                  directory: "./examples/next/with-emailpassword/.vercel/output/static"
                  wranglerVersion: "3"

            - name: Extract deployment info and save to JSON
              id: extract_deploy_info
              run: |
                  DEPLOY_ID=${{ steps.deploy.outputs.id }}
                  DEPLOY_URL=${{ steps.deploy.outputs.url }}
                  echo "{\"deploy_url\": \"$DEPLOY_URL\", \"deploy_id\": \"$DEPLOY_ID\"}" > deployInfo.json
                  echo "::set-output name=deploy_url::$DEPLOY_URL"

            - name: Run tests
              env:
                  DEPLOYED_URL: ${{ steps.extract_deploy_info.outputs.deploy_url }}
              run: |
                  ( \
                    (echo "=========== Test attempt 1 ===========" && npx mocha --no-config --timeout 80000 test/**/*.test.js) || \
                    (echo "=========== Test attempt 2 ===========" && npx mocha --no-config --timeout 80000 test/**/*.test.js) || \
                    (echo "=========== Test attempt 3 ===========" && npx mocha --no-config --timeout 80000 test/**/*.test.js) \
                  )

            - name: The job has failed
              if: ${{ failure() }}
              uses: actions/upload-artifact@v3
              with:
                  name: screenshots
                  path: |
                      ./**/*screenshot.jpeg
